export { default as Home} from './Home'
export { default as Profile} from './Profile'
export { default as SignIn} from './SignIn'
export { default as Register} from './Register'
export { default as EditProfile} from './EditProfile'