export default {
    LOGO:    require('../assets/images/logo.png'),
    HOME:    require('../assets/images/home.png'),
    PROFILE:    require('../assets/images/profile.png'),
    USERNAME:    require('../assets/images/username.png'),
    PASSWORD:    require('../assets/images/password.png'),
    FULLNAME:    require('../assets/images/fullname.png'),
    EMAIL:    require('../assets/images/email.png'),
    PHONE:    require('../assets/images/phone.png'),
    EXIT:    require('../assets/images/exit.png'),
    EMAIL_INFO: require('../assets/images/email_info.png'),
    TELEPHONE: require('../assets/images/telephone.png'),
    
    FB: require('../assets/images/facebook.png'),
    MESSENGER: require('../assets/images/messenger.png'),
    ZALO: require('../assets/images/zalo.png'),
    TWITTER: require('../assets/images/twitter.png'),
    LINKEDIN: require('../assets/images/linkedin.png'),
    FLICKR: require('../assets/images/flickr.png'),
    INSTAGRAM: require('../assets/images/instagram.png'),
}